# fly.toml app configuration file generated for cooperative-crosswords-be on 2025-06-15T12:34:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cooperative-crosswords-be'
primary_region = 'lhr'

[build]

[env]
  HOST_PORT = '0.0.0.0:8080'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
